/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import connection.ConnSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author leo27
 */
public class Prb extends javax.swing.JFrame {

    public static ConnSQL conn;
    /**
     * Creates new form Prb
     */
    public Prb() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Consulta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        pInventario1 = new javax.swing.JMenuItem();
        tutAl = new javax.swing.JMenuItem();
        matAlu = new javax.swing.JMenuItem();
        diralu = new javax.swing.JMenuItem();
        profal = new javax.swing.JMenuItem();
        Aerolineas = new javax.swing.JMenu();
        pInventario2 = new javax.swing.JMenuItem();
        profC = new javax.swing.JMenuItem();
        AlPr = new javax.swing.JMenuItem();
        salV = new javax.swing.JMenuItem();
        ProfEl = new javax.swing.JMenu();
        bajPr = new javax.swing.JMenuItem();
        inser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de Datos Escuela");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu2.setText("Ver tablas");

        Consulta.setText("Ver todas...");
        Consulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(Consulta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Busqueda");

        pInventario1.setText("Buscar alumno");
        pInventario1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pInventario1ActionPerformed(evt);
            }
        });
        jMenu3.add(pInventario1);

        tutAl.setText("Busqueda de tutor");
        tutAl.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tutAlActionPerformed(evt);
            }
        });
        jMenu3.add(tutAl);

        matAlu.setText("Ver calificación por materia");
        matAlu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                matAluActionPerformed(evt);
            }
        });
        jMenu3.add(matAlu);

        diralu.setText("Direcciones de alumnos");
        diralu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diraluActionPerformed(evt);
            }
        });
        jMenu3.add(diralu);

        profal.setText("Profesores y alumnos");
        profal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                profalActionPerformed(evt);
            }
        });
        jMenu3.add(profal);

        jMenuBar1.add(jMenu3);

        Aerolineas.setText("Ver");

        pInventario2.setText("Profesores sin asignaturas");
        pInventario2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pInventario2ActionPerformed(evt);
            }
        });
        Aerolineas.add(pInventario2);

        profC.setText("Profesores actuales con materias");
        profC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                profCActionPerformed(evt);
            }
        });
        Aerolineas.add(profC);

        AlPr.setText("Alumnos excelentes");
        AlPr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AlPrActionPerformed(evt);
            }
        });
        Aerolineas.add(AlPr);

        salV.setText("Posibles nuevos salarios");
        salV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salVActionPerformed(evt);
            }
        });
        Aerolineas.add(salV);

        jMenuBar1.add(Aerolineas);

        ProfEl.setText("Baja Profesores");

        bajPr.setText("Eliminar Profesor");
        bajPr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bajPrActionPerformed(evt);
            }
        });
        ProfEl.add(bajPr);

        jMenuBar1.add(ProfEl);

        inser.setText("Inserciones");

        jMenuItem1.setText("Insertar profesor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        inser.add(jMenuItem1);

        jMenuItem2.setText("Actualizar sueldo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        inser.add(jMenuItem2);

        jMenuBar1.add(inser);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pInventario1ActionPerformed
        // TODO add your handling code here:
        new VtnCalifAlum().setVisible(true);
    }//GEN-LAST:event_pInventario1ActionPerformed

    private void pInventario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pInventario2ActionPerformed
        // TODO add your handling code here:
        new VtnProfSC().setVisible(true);
    }//GEN-LAST:event_pInventario2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        conn = new ConnSQL("ORCL", "jordi", "jordi");
        System.out.println(conn.estado);
    }//GEN-LAST:event_formWindowOpened

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConsultaActionPerformed
    {//GEN-HEADEREND:event_ConsultaActionPerformed
        new VtnConsultas().setVisible(true);
    }//GEN-LAST:event_ConsultaActionPerformed

    private void AlPrActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AlPrActionPerformed
    {//GEN-HEADEREND:event_AlPrActionPerformed
        new VtnAluP().setVisible(true);
    }//GEN-LAST:event_AlPrActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
            conn.close();
    }//GEN-LAST:event_formWindowClosing

    private void salVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salVActionPerformed
    {//GEN-HEADEREND:event_salVActionPerformed
        new VtnNvoSal().setVisible(true);
    }//GEN-LAST:event_salVActionPerformed

    private void profCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_profCActionPerformed
    {//GEN-HEADEREND:event_profCActionPerformed
        new VtnProfC().setVisible(true);
    }//GEN-LAST:event_profCActionPerformed

    private void tutAlActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tutAlActionPerformed
    {//GEN-HEADEREND:event_tutAlActionPerformed
        new VtnTutoresAlu().setVisible(true);
    }//GEN-LAST:event_tutAlActionPerformed

    private void matAluActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_matAluActionPerformed
    {//GEN-HEADEREND:event_matAluActionPerformed
        new VtnMatCali().setVisible(true);
    }//GEN-LAST:event_matAluActionPerformed

    private void diraluActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diraluActionPerformed
    {//GEN-HEADEREND:event_diraluActionPerformed
        new VtnDirAlu().setVisible(true);
    }//GEN-LAST:event_diraluActionPerformed

    private void profalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_profalActionPerformed
    {//GEN-HEADEREND:event_profalActionPerformed
        new VtnAluProf().setVisible(true);
    }//GEN-LAST:event_profalActionPerformed

    private void bajPrActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bajPrActionPerformed
    {//GEN-HEADEREND:event_bajPrActionPerformed
        new VtnBajaProfesores().setVisible(true);
    }//GEN-LAST:event_bajPrActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        new VtnNvoSueldo().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        new VtnInsertaProf().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aerolineas;
    private javax.swing.JMenuItem AlPr;
    private javax.swing.JMenuItem Consulta;
    private javax.swing.JMenu ProfEl;
    private javax.swing.JMenuItem bajPr;
    private javax.swing.JMenuItem diralu;
    private javax.swing.JMenu inser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem matAlu;
    private javax.swing.JMenuItem pInventario1;
    private javax.swing.JMenuItem pInventario2;
    private javax.swing.JMenuItem profC;
    private javax.swing.JMenuItem profal;
    private javax.swing.JMenuItem salV;
    private javax.swing.JMenuItem tutAl;
    // End of variables declaration//GEN-END:variables
}
