/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import javax.swing.JOptionPane;
import sun.security.jgss.spi.MechanismFactory;

/**
 *
 * @author John PV
 */
public class VtnNvoSueldo extends javax.swing.JFrame
{

    /**
     * Creates new form VtnBajaProfesores
     */
    public VtnNvoSueldo()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCve = new javax.swing.JTextField();
        salT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        salV = new javax.swing.JMenu();
        SalaB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja Profesores");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese la clave del servidor publico");

        txtCve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCveActionPerformed(evt);
            }
        });
        txtCve.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtCveKeyTyped(evt);
            }
        });

        salT.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                salTKeyTyped(evt);
            }
        });

        jLabel2.setText("Ingrese el nuevo salario");

        salV.setText("Salarios antiguos");

        SalaB.setText("Ver...");
        SalaB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalaBActionPerformed(evt);
            }
        });
        salV.add(SalaB);

        jMenuBar1.add(salV);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salT)
                    .addComponent(txtCve, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCveKeyTyped
    {//GEN-HEADEREND:event_txtCveKeyTyped
        String s = txtCve.getText();
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9' || s.length() == 10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCveKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        try
        {
            boolean existe = Prb.conn.buscaProfesor(Integer.parseInt(txtCve.getText()));
            if (existe)
            {
                int option = Mensaje.pregunta(this, "Seguro que desea actualizar el sueldo del profesor de la base de datos?");
                if (option == JOptionPane.YES_OPTION)
                {
                    int a = Integer.parseInt(txtCve.getText());
                    int b = Integer.parseInt(salT.getText());
                    Prb.conn.cambiarSueldoProf(a, b);
                    Mensaje.exito(this, "Se ha actualizado el profesor de la base de datos");
                }
            } else
            {
                Mensaje.error(this, "No existe el profesor");
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCveActionPerformed
    {//GEN-HEADEREND:event_txtCveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCveActionPerformed

    private void salTKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_salTKeyTyped
    {//GEN-HEADEREND:event_salTKeyTyped
        String s = salT.getText();
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9' || s.length() == 4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_salTKeyTyped

    private void SalaBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalaBActionPerformed
    {//GEN-HEADEREND:event_SalaBActionPerformed
        new VtnProfSueldo().setVisible(true);
    }//GEN-LAST:event_SalaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnNvoSueldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnNvoSueldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnNvoSueldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnNvoSueldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnNvoSueldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SalaB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField salT;
    private javax.swing.JMenu salV;
    private javax.swing.JTextField txtCve;
    // End of variables declaration//GEN-END:variables
}
